services:
  - type: web
    plan: free
    name: AutoAnimeBot-2.0
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 -m AutoAnimeBot
    repo: https://github.com/StupidBoi7/AutoAnimeBot-2.0.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STATUS_MSG_ID
        sync: false
      - key: INDEX_CHANNEL_USERNAME
        sync: false
      - key: UPLOADS_CHANNEL_USERNAME
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: COMMENTS_GROUP_LINK
        sync: false
      - key: SLEEP_TIME
        sync: false
      - key: CHANNEL_TITLE
        sync: false
      - key: SCHEDULE_MSG_ID
        sync: false
      - key: TECHZ_API_KEY
        sync: false
